import {Arbol} from "./arbol";
import {Avion} from "./avion";
import {Gafas} from "./gafas";
import {Pan} from "./pan";
import {Persona} from "./persona";
import {Tamal} from "./tamal";

let arbol: Arbol = new Arbol();
arbol.altura = 20;
arbol.color = "verde";
arbol.diametro = 1;
arbol.edad = 50;
arbol.tipo = "pino";
console.log("ARBOL -----------------------------------");
console.log(arbol.altura);
console.log(arbol.color);
console.log(arbol.diametro);
console.log(arbol.edad);
console.log(arbol.tipo);

let avion: Avion = new Avion();
avion.capacidad = 2500;
avion.color = "azul";
avion.marca = "marca";
avion.precio = 1500;
avion.turbinas = 2;
console.log("AVION -----------------------------------");
console.log(avion.turbinas);
console.log(avion.precio);
console.log(avion.marca);
console.log(avion.color);
console.log(avion.capacidad);

let gafas: Gafas = new Gafas();
console.log("GAFAS -----------------------------------");
gafas.color = "rojas";
gafas.estilo = "sin borde inferior";
gafas.grosor = 1;
gafas.marca = "adidas";
gafas.precio = 200000;
console.log(gafas.precio);
console.log(gafas.marca);
console.log(gafas.grosor);
console.log(gafas.color);
console.log(gafas.estilo);

let pan: Pan = new Pan();
pan.color = "cafe";
pan.peso = 2;
pan.precio = 2000;
pan.sabor = "dulce";
pan.tipo = "frances";
console.log("PAN -----------------------------------");
console.log(pan.tipo);
console.log(pan.sabor);
console.log(pan.precio);
console.log(pan.color);
console.log(pan.peso);

let persona: Persona = new Persona();
persona.colorCabello = "cafe";
persona.colorOjos = "verdes";
persona.colorPiel = "blanco";
persona.dedos = 20;
persona.lunares = 5;
console.log("PERSONA -----------------------------------");
console.log(persona.lunares);
console.log(persona.dedos);
console.log(persona.colorPiel);
console.log(persona.colorCabello);
console.log(persona.colorOjos);

let tamal: Tamal = new Tamal();
tamal.color="verde";
tamal.peso=2;
tamal.precio=5000;
tamal.region="santander";
tamal.tamanio="mediano";
console.log("TAMAL -----------------------------------");
console.log(tamal.tamanio);
console.log(tamal.region);
console.log(tamal.color);
console.log(tamal.peso);
console.log(tamal.precio);
